services:
  - type: web
    name: instext-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: your_mongodb_uri
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: PORT
        value: 5000

  - type: web
    name: instext-frontend
    runtime: node
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        value: https://instext-backend.onrender.com
